print(" * " * 16)
print(" *                                            * ")
print(" *                                            * ")
print(" *                                            * ")
print(" *             MARGARIDA NOGUEIRA             * ")
print(" *                                            * ")
print(" *             ENTRE EM CONTACTO!             * ")
print(" *                                            * ")
print(" *          Tel: 111111111 | 222222222        * ")
print(" *                                            * ")
print(" *                                            * ")
print(" *                                            * ")
print(" * " * 16)